//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_JuntaSoldaduraSoldado
    {
        public int JuntaSoldaduraSoldadoID { get; set; }
        public int JuntaSoldaduraID { get; set; }
        public int ObreroID { get; set; }
        public Nullable<int> ColadaSoldaduraID { get; set; }
        public int TipoSoldaduraID { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual Sam3_JuntaSoldadura Sam3_JuntaSoldadura { get; set; }
        public virtual Sam3_Obrero Sam3_Obrero { get; set; }
        public virtual Sam3_TipoSoldadura Sam3_TipoSoldadura { get; set; }
    }
}
