//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_OrdenTrabajoJunta
    {
        public int OrdenTrabajoJuntaID { get; set; }
        public int OrdenTrabajoSpoolID { get; set; }
        public int JuntaSpoolID { get; set; }
        public bool FueReingenieria { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Sam3_JuntaSpool Sam3_JuntaSpool { get; set; }
        public virtual Sam3_OrdenTrabajoSpool Sam3_OrdenTrabajoSpool { get; set; }
    }
}
