//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_Rel_Perfil_Entidad_Pagina
    {
        public int PerfilID { get; set; }
        public int EntidadID { get; set; }
        public int PaginaID { get; set; }
        public bool PermisoDetalle { get; set; }
        public bool PermisoCreacion { get; set; }
        public bool PermisoEliminacion { get; set; }
        public bool PermisoListado { get; set; }
        public bool PermisoCapturaIncidencia { get; set; }
        public bool PermisoSolucionIncidencia { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Sam3_Entidad Sam3_Entidad { get; set; }
        public virtual Sam3_Pagina Sam3_Pagina { get; set; }
        public virtual Sam3_Perfil Sam3_Perfil { get; set; }
    }
}
