//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_ProyectoConsecutivo
    {
        public int ProyectoID { get; set; }
        public int ConsecutivoFolioAvisollegada { get; set; }
        public int ConsecutivoFolioEntradaMateiral { get; set; }
        public int ConsecutivoFolioDescargaMaterial { get; set; }
        public int ConsecutivoPaseSalida { get; set; }
        public int ConsecutivoPermisoAduana { get; set; }
        public int ConsucutivoFolioPackingList { get; set; }
        public int ConsecutivoODT { get; set; }
        public int ConsecutivoNumerounico { get; set; }
        public bool Activo { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public int ConsecutivoOrdeRecepcion { get; set; }
        public int ConsecutivoOrdenAlmacenaje { get; set; }
    
        public virtual Sam3_Proyecto Sam3_Proyecto { get; set; }
    }
}
