//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_Rel_OrdenRecepcion_ItemCode
    {
        public int Rel_OrdenRecepcion_ItemCode_ID { get; set; }
        public int OrdenRecepcionID { get; set; }
        public Nullable<int> ItemCodeID { get; set; }
        public bool Activo { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<int> Rel_ItemCode_Diametro_ID { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Sam3_OrdenRecepcion Sam3_OrdenRecepcion { get; set; }
        public virtual Sam3_Rel_ItemCode_Diametro Sam3_Rel_ItemCode_Diametro { get; set; }
    }
}
