//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_Recepcion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sam3_Recepcion()
        {
            this.Sam3_NumeroUnico = new HashSet<Sam3_NumeroUnico>();
        }
    
        public int RecepcionID { get; set; }
        public int ItemCodeID { get; set; }
        public Nullable<int> FamiliaItemCodeID { get; set; }
        public Nullable<int> CedulaID { get; set; }
        public Nullable<int> TipoAceroID { get; set; }
        public Nullable<decimal> Diametro1 { get; set; }
        public Nullable<decimal> Diametro2 { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<bool> TieneNumerosUnicos { get; set; }
        public Nullable<System.DateTime> FechaGeneracionNumerosUnicos { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public int FolioCuantificacionID { get; set; }
    
        public virtual Sam3_FolioCuantificacion Sam3_FolioCuantificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sam3_NumeroUnico> Sam3_NumeroUnico { get; set; }
    }
}
