//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_NumeroUnicoInventario
    {
        public int NumeroUnicoID { get; set; }
        public int ProyectoID { get; set; }
        public int CantidadRecibida { get; set; }
        public int CantidadDanada { get; set; }
        public int InventarioFisico { get; set; }
        public int InventarioBuenEstado { get; set; }
        public int InventarioCongelado { get; set; }
        public int InventarioTransferenciaCorte { get; set; }
        public int InventarioDisponibleCruce { get; set; }
        public bool EsVirtual { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Sam3_NumeroUnico Sam3_NumeroUnico { get; set; }
        public virtual Sam3_Proyecto Sam3_Proyecto { get; set; }
    }
}
