//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_Corte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sam3_Corte()
        {
            this.Sam3_Rel_Incidencia_Corte = new HashSet<Sam3_Rel_Incidencia_Corte>();
            this.Sam3_CorteDetalle = new HashSet<Sam3_CorteDetalle>();
        }
    
        public int CorteID { get; set; }
        public int ProyectoID { get; set; }
        public Nullable<int> NumeroUnicoCorteID { get; set; }
        public Nullable<int> Sobrante { get; set; }
        public Nullable<int> Merma { get; set; }
        public Nullable<int> MermaMovimientoID { get; set; }
        public Nullable<int> PreparacionCorteMovimientoID { get; set; }
        public bool Cancelado { get; set; }
        public string Rack { get; set; }
        public Nullable<int> CortadorID { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sam3_Rel_Incidencia_Corte> Sam3_Rel_Incidencia_Corte { get; set; }
        public virtual Sam3_NumeroUnicoMovimiento Sam3_NumeroUnicoMovimiento { get; set; }
        public virtual Sam3_NumeroUnicoMovimiento Sam3_NumeroUnicoMovimiento1 { get; set; }
        public virtual Sam3_Proyecto Sam3_Proyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sam3_CorteDetalle> Sam3_CorteDetalle { get; set; }
    }
}
