//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_Cedula
    {
        public int CedulaID { get; set; }
        public string Codigo { get; set; }
        public Nullable<int> Orden { get; set; }
        public bool VerificadoPorCalidad { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<decimal> Diametro { get; set; }
        public string CedulaA { get; set; }
        public string CedulaB { get; set; }
        public string CedulaC { get; set; }
        public Nullable<decimal> CedulaIn { get; set; }
        public Nullable<decimal> CedulaMM { get; set; }
        public Nullable<decimal> Espesor { get; set; }
    }
}
