//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_Rel_Usuario_Preferencia
    {
        public int Rel_Usuario_PreferenciaID { get; set; }
        public int UsuarioID { get; set; }
        public int PreferenciaID { get; set; }
        public string ValorPreferencia { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Sam3_Preferencia Sam3_Preferencia { get; set; }
        public virtual Sam3_Usuario Sam3_Usuario { get; set; }
    }
}
