//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_UsuariosNotificaciones
    {
        public int UsuariosNotificacionesID { get; set; }
        public Nullable<int> TipoNotificacionID { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public string Email { get; set; }
        public string Plantilla { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Sam3_TipoNotificacion Sam3_TipoNotificacion { get; set; }
        public virtual Sam3_Usuario Sam3_Usuario { get; set; }
    }
}
