//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_ColaCreacionNumerosUnicos
    {
        public int ID { get; set; }
        public int ItemCodeID { get; set; }
        public int OrdenRecepcionID { get; set; }
        public int TipoMaterialID { get; set; }
        public int Cantidad { get; set; }
        public int UsuarioID { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public bool ReplicadoASAM2 { get; set; }
        public bool Activo { get; set; }
    
        public virtual Sam3_ItemCode Sam3_ItemCode { get; set; }
        public virtual Sam3_OrdenRecepcion Sam3_OrdenRecepcion { get; set; }
        public virtual Sam3_Usuario Sam3_Usuario { get; set; }
    }
}
