//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_Rel_Perfil_Propiedad_Pagina
    {
        public int PerfilID { get; set; }
        public int PropiedadID { get; set; }
        public int PaginaID { get; set; }
        public bool PermisoEdicion { get; set; }
        public bool PermisoLectura { get; set; }
        public bool Requerido { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Sam3_Perfil Sam3_Perfil { get; set; }
        public virtual Sam3_Propiedad Sam3_Propiedad { get; set; }
    }
}
