//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_PQR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sam3_PQR()
        {
            this.Sam3_SoldadorCertificacion = new HashSet<Sam3_SoldadorCertificacion>();
        }
    
        public int PQRID { get; set; }
        public string Nombre { get; set; }
        public bool PREHEAT { get; set; }
        public bool PWHT { get; set; }
        public decimal EspesorRelleno { get; set; }
        public Nullable<decimal> EspesorRaiz { get; set; }
        public int ProcesoSoldaduraRellenoID { get; set; }
        public Nullable<int> ProcesoSoldaduraRaizID { get; set; }
        public Nullable<int> NumeroP { get; set; }
        public Nullable<int> GrupoPMaterialBase1 { get; set; }
        public Nullable<int> GrupoPMaterialBase2 { get; set; }
        public Nullable<int> Aporte { get; set; }
        public Nullable<int> Mezcla { get; set; }
        public Nullable<int> Respaldo { get; set; }
        public Nullable<int> GrupoF { get; set; }
        public Nullable<int> Codigo { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Sam3_ProcesoSoldadura Sam3_ProcesoSoldadura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sam3_SoldadorCertificacion> Sam3_SoldadorCertificacion { get; set; }
    }
}
